version: "3.9"
services:
  ros1_hw:
    image: ghcr.io/<your‑user>/ros1_hw:main  # built by CI later
    network_mode: host
    privileged: true
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    environment:
      - ROS_MASTER_URI=http://pi.local:11311
      - ROS_IP=pi.local
