version: "3.9"
services:
  ros2_sim:
    build: ../docker/ros2_sim
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=0
      - ROS_MASTER_URI=http://pi.local:11311
      - DISPLAY=${DISPLAY}
    volumes:
      - ../ros2_ws:/ros2_ws:rw
      - /tmp/.X11-unix:/tmp/.X11-unix

  ros1_bridge:
    image: ros:humble-ros1-bridge
    network_mode: host
    environment:
      - ROS_MASTER_URI=http://pi.local:11311
      - ROS_DOMAIN_ID=0
