# ros2_ws/src/dofbot_description/config/controllers.yaml

controller_manager:
  ros__parameters:
    update_rate: 100

# Publish joint states so RViz & other nodes see them
joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster
    publish_rate: 50

# A simple position‐trajectory controller for your 5 revolute joints
position_trajectory_controller:
  ros__parameters:
    type: position_controllers/JointTrajectoryController
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
    state_publish_rate: 50
    # Constraints to avoid overshoot
    constraints:
      joint1: {trajectory: 0.1, goal: 0.05}
      joint2: {trajectory: 0.1, goal: 0.05}
      joint3: {trajectory: 0.1, goal: 0.05}
      joint4: {trajectory: 0.1, goal: 0.05}
      joint5: {trajectory: 0.1, goal: 0.05}

# List the controllers to autospawn on startup
controller_manager_spawner:
  ros__parameters:
    autostart: true
    controllers:
      - joint_state_broadcaster
      - position_trajectory_controller
