# ros2_ws/src/dofbot_description/config/controllers.yaml
# – fully nested so controller_manager sees the parameters –

controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      publish_rate: 50

    position_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints: [joint1, joint2, joint3, joint4, joint5]
      command_interfaces:
        - position  # ← ADD THIS
      state_publish_rate: 50
      constraints:
        stopped_velocity_tolerance: 0.01
        goal_time: 0.5
        joint1: {trajectory: 0.1, goal: 0.05}
        joint2: {trajectory: 0.1, goal: 0.05}
        joint3: {trajectory: 0.1, goal: 0.05}
        joint4: {trajectory: 0.1, goal: 0.05}
        joint5: {trajectory: 0.1, goal: 0.05}
